test:
   script:
       - source environment/activate.sh env
       - rm -rf output cache tmp
       - mkdir output cache tmp
       - export TMPDIR=${CI_PROJECT_DIR}/tmp
       - python3 -u run.py config_gitlab.yml

before_script:
    - sh environment/setup.sh env
    - sh environment/activate.sh env

cache:
    key: environment_v2
    paths:
        - env/
