test:
    script:
        - export PATH=/nas/vplworker/anaconda3/bin:$PATH
        - source activate ivt
        - python3 --version
        - rm -rf output
        - mkdir output
        - python3 run.py config_gitlab.yml
        - rm -rf output
