test:
   script:
       - export PATH=/nas/vplworker/anaconda3/bin:$PATH
       - export PATH=/nas/vplworker/java/bin:$PATH
       - export PATH=/nas/vplworker/maven/bin:$PATH
       - source activate ivt
       - python3 --version
       - pwd
       - rm -rf output temp
       - mkdir output temp
       - python3 -u run.py config_gitlab.yml
       - rm -rf output
