raw_data_path: /run/media/sebastian/shoerl_data/scenarios/switzerland/data
target_path: /run/media/sebastian/shoerl_data/scenarios/switzerland/temp
output_path: /run/media/sebastian/shoerl_data/scenarios/switzerland/temp
threads: 4
hot_deck_matching_runners: 2
disable_progress_bar: false
java_memory: 10G
input_downsampling: 0.01
enable_scaling: true
scaling_year: 2020
use_freight: true
stages:
    - data.statpop.projections.households
    - data.statpop.scaled
    #- data.microcensus.trips
    #- population.spatial.locations
    #- population.trips
    #- data.microcensus.persons
    #- data.microcensus.households
    #- population.sociodemographics
    #- matsim.population
    #- matsim.population_attributes
    #- matsim.households
    #- matsim.population
    #- data.microcensus.commute_extrapolation
    #- population.spatial.education_locations
    #- population.spatial.by_person.education_locations
    #- population.spatial.by_activity.subprimary_locations
    #- population.spatial.activity_locations
    #- population.opportunities
    #- population.activities
    #- population.commute
    #- population.secondary_locations
    #- population.fixed_locations
    #- population.commute_ratios
