# General pipeline settings
# path to the working directory/cache
working_directory: /cluster/scratch/rsahleanu/cache
#p path where the pipeline flowchart should be stored
flowchart_path: ./flowchart.png
dryrun: false
output_path: /cache
run:
    - synthesis.output
    - matsim.simulation.run
    - analysis.webmap_export

# These are configuration options that we use in the pipeline
config:

    hot_deck_matching_runners: 1
    osm_path: switzerland-latest-2025.osm.pbf
    output_path: /cluster/scratch/rsahleanu/output
    census: statpop    # path to the input data folder
    data_path: /cluster/project/cmdp/ch_data/pipeline/
    threads: 48
    export_detailed_network: false
    random_seed: 0
    # it seems fastest is with 1
    hot_deck_matching_runners: 1
    disable_progress_bar: false
    java_memory: 192G
    input_downsampling: 0.01

    # default to false until we fix projections
    enable_scaling: false
    # to which year we want to scale the population; this will not be used if enable_scaling is set to false
    scaling_year: 2020

    # do we want to include freight demand int eh synthetic population, defailt is true
    use_freight: true
    # there are two options to convert pt schedule: [hafas, gtfs]; default is gtfs
    pt_schedule: gtfs
    # name of the gtfs zip file, should be placed in gtfs folder within data_path
    gtfs_name: gtfs_fp2024_2024-11-11
    # date from which gtfs should be take. Options are [dayWithMostTrips, dayWithMostServices, <exact date>]
    gtfs_date: "dayWithMostServices" 
    # if hafas is used, the data needs to be specified
    hafas_date: 01.10.2018
    
    # if we should use schedule based pt or simulated
    useScheduleBasedTransport: false
    # defines the prefix for the cutout scenario name; it should be of the zurich_ format
    extent_prefix: zurich_

    # specifies if we want to use VDF as the traffic model, default is false
    use_vdf: false

    webmap_export: both
