raw_data_path: /nas/ivtmatsim/scenarios/switzerland/data
target_path: temp
output_path: output
threads: 24
hot_deck_matching_runners: 24
disable_progress_bar: true
java_memory: 100G
input_downsampling: 0.01
enable_scaling: true
scaling_year: 2045
stages:
    - matsim.run
    - matsim.mz.population
    - data.microcensus.csv
