# General pipeline settings
# path to the working directory/cache
working_directory: 
# path where the pipeline flowchart should be stored
flowchart_path:
dryrun: false

# Requested stages
run:
    - synthesis.output
    - matsim.simulation.run
    # - dmc.model # uncomment if you want to estimte the dmc model using biogeme

# These are configuration options that we use in the pipeline
config:
    # path to the input data folder
    data_path: 
    threads: 48
    random_seed: 0
    # it seems fastest is with 1
    hot_deck_matching_runners: 1
    disable_progress_bar: false
    java_memory: 10G
    input_downsampling: 0.10

    # default to false until we fix projections
    enable_scaling: true
    # to which year we want to scale the population; this will not be used if enable_scaling is set to false
    scaling_year: 2025

    # which population census we want to use. There are two options: statpop and are_synpop; default is statpop.
    census: statpop

    # do we want to include freight demand in the synthetic population, defailt is true
    use_freight: true
    # there are two options to convert pt schedule: [hafas, gtfs]; default is gtfs
    pt_schedule: gtfs
    # name of the gtfs zip file, should be placed in gtfs folder within data_path
    gtfs_name: gtfs_fp2024_2024-11-11
    # date from which gtfs should be take. Options are [dayWithMostTrips, dayWithMostServices, <exact date>]
    gtfs_date: "dayWithMostServices" 
    # if hafas is used, the data needs to be specified
    hafas_date: 01.10.2018
    
    # if we should use schedule based pt or simulated
    useScheduleBasedTransport: false
    # defines the prefix for the cutout scenario name; it should be of the zurich_ format
    extent_prefix: switzerland_

    # specifies if we want to use VDF as the traffic model, default is false
    use_vdf: false

    # Export detailed network in eqasim, default is false
    export_detailed_network: true

    # last iteration when runing MATSim
    last_iteration: 60

    # If you want to simplify the network (merge short links) in eqasim and correct their capacity, default is false
    simplify_network_in_eqasim: false
    correct_links_capacity: false

    # path to the osm file, should be placed in data_path/osm (it can be list of comma separated files)    
    osm_file: switzerland-latest-2025.osm.pbf
    border_offset: 20000 # offset for border extension in meters, default is 20000

    # wether to parse turn restrictions or not
    parseTurnRestrictions: true

    # whether to add traffic lights to the network, default is false
    add_trafic_lights: false

    # whether to assign elevations to the nodes, default is false
    assign_elevations: false

    # Specific day scenario (default: workday, also possible: weekend, Monday, ... Sunday)
    # workday takes Monday-Friday
    specific_day_scenario: workday

    # when estimating the dmc model using biogeme (TODO: add pt cost params)
    routed_trips_file: "Routed_alternatives_v3_FINAL.txt" # absolute path to the data  

    # Cross-border traffic
    include_cross_border: true

    # PT pricing
    # default is false; true does nto work on Euler
    generate_pt_pricing_inputs: false

    # Pt routing parameters
    # can run on Euler but takes huge amount of time
    calibrate_pt_routing_params: false # Please make sure you really want to switch this parameter to true because the calibration takes 12+ hours!

    # calibration and dmc model estimation  
    estimate_dmc: true
    calibrate_alphas_in_matsim: true
    calibrate_betas_in_matsim: false
    activate_traffic_light_delays: false
    activate_unsignalized_intersections_delays: false