"""
Stage: analysis.counts.cross_border_flow

Per-link car flow generated by cross-border agents (subpopulation ==
"crossborder"), computed from output_events.xml.gz since MATSim's own flow
outputs aggregate every vehicle and can't be split by agent. Counts are
rescaled by 1 / input_downsampling and cover car mode only, so they're
comparable to but not identical to simulated_flow elsewhere (that includes
car_passenger/trucks unless counts.filterModes is set).

Writes cross_border_link_flow_{daily,hourly}.csv and two plots into the
shared get_analysis_output_path folder (same as every other analysis.counts
stage).
"""

import glob
import json
import logging
import os
from collections import Counter
from html import escape
from pathlib import Path

import geopandas as gpd
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import pydeck as pdk
import shapely
import xml.etree.ElementTree as ET
import xopen
from pydeck.data_utils.viewport_helpers import compute_view
from shapely.ops import unary_union

from .matching.plots import Plotter
from .paths import configure_simulation_path, get_analysis_output_path, get_simulation_path

logger = logging.getLogger("synpp")

CAR_VEHICLE_SUFFIX = ":car"
LINK_ENTRY_EVENT_TYPES = {"entered link"}
ROAD_TYPES_FOR_MAP = ["motorway", "trunk", "primary", "motorway_link", "trunk_link", "primary_link"]
PROGRESS_EVERY = 2_000_000
MIN_SPEED_KMH_FOR_FLOW_MAP = 30
SHARE_COLOR_SATURATION_PCT = 20


def configure(context):
    context.stage("analysis.counts.matching.network")
    context.stage("data.spatial.swiss_border")
    configure_simulation_path(context)
    context.config("only_weekday", default=False)
    context.config("input_downsampling")
    context.config("cross_border_flow_min_daily_count", default=20)
    context.config("extent_path", default="")


def execute(context):
    simulation_path = get_simulation_path(context)
    output_path = get_analysis_output_path(context)
    os.makedirs(output_path, exist_ok=True)

    persons_path = _find_output_file(simulation_path, "output_persons.csv.gz")
    events_path = _find_output_file(simulation_path, "output_events.xml.gz")

    cross_border_ids = load_cross_border_person_ids(persons_path)
    swiss_resident_ids = load_swiss_resident_cross_border_person_ids(persons_path)
    logger.info(
        "Found %d cross-border persons (%d of them Swiss residents) in %s",
        len(cross_border_ids), len(swiss_resident_ids), persons_path,
    )

    total_counts, crossborder_counts, swiss_resident_counts = count_car_link_entries(
        events_path, cross_border_ids, swiss_resident_ids,
    )
    logger.info("Counted car entries on %d distinct links", len(total_counts))

    df_hourly = build_hourly_dataframe(total_counts, crossborder_counts, swiss_resident_counts)

    sample_size = context.config("input_downsampling")
    df_hourly["total_flow"] = df_hourly["total_flow"] / sample_size
    df_hourly["crossborder_flow"] = df_hourly["crossborder_flow"] / sample_size
    df_hourly["swiss_resident_flow"] = df_hourly["swiss_resident_flow"] / sample_size

    df_daily = aggregate_daily(df_hourly)

    network = context.stage("analysis.counts.matching.network")
    df_daily = attach_road_attributes(df_daily, network)

    hourly_csv = os.path.join(output_path, "cross_border_link_flow_hourly.csv")
    daily_csv = os.path.join(output_path, "cross_border_link_flow_daily.csv")
    #df_hourly.to_csv(hourly_csv, index=False)
    #df_daily.to_csv(daily_csv, index=False)
    #logger.info("Saved per-link cross-border flow to %s and %s", daily_csv, hourly_csv)

    min_daily_count = context.config("cross_border_flow_min_daily_count")
    df_plot = df_daily[df_daily.total_flow >= min_daily_count].copy()

    #plot_share_by_road_type(df_plot, output_path)
    #plot_share_map(df_plot, network, output_path)
    swiss_border = context.stage("data.spatial.swiss_border")
    plot_crossborder_flow_map(
        df_plot, network, context.config("extent_path"), swiss_border,
        "/home/asallard/Documents/Results/20260914_geneva_10pct/compare_counts_weekdays",
    )

    return dict(done=True, path=output_path, daily_csv=daily_csv, hourly_csv=hourly_csv)


# ---------------------------------------------------------------------------
# File discovery
# ---------------------------------------------------------------------------

def _find_output_file(simulation_path, filename):
    """MATSim writes these directly under simulation_output; fall back to the
    last ITERS snapshot if the final output is missing (unfinished run)."""

    direct_path = os.path.join(simulation_path, filename)
    if os.path.exists(direct_path):
        return direct_path

    stem, _, suffix = filename.partition(".")
    candidates = glob.glob(os.path.join(simulation_path, "ITERS", "*", f"*.{suffix}"))
    if not candidates:
        raise FileNotFoundError(f"Could not find {filename} in {simulation_path} (or its ITERS folder)")

    candidate = max(candidates, key=os.path.getmtime)
    logger.warning("%s not found at %s, using latest iteration snapshot %s instead", filename, direct_path, candidate)
    return candidate


# ---------------------------------------------------------------------------
# Cross-border person identification
# ---------------------------------------------------------------------------

def load_cross_border_person_ids(persons_path):
    # low_memory=False: the default chunked C-engine read hits a pandas bug
    # (IndexError in _concatenate_chunks) on this file size with usecols set.
    df = pd.read_csv(
        persons_path, sep=";", usecols=["person", "subpopulation"], dtype={"person": str}, low_memory=False,
    )
    return set(df.loc[df.subpopulation == "crossborder", "person"])


def load_swiss_resident_cross_border_person_ids(persons_path):
    """The subset of cross-border persons whose crossBorderOD starts with
    "CH" (e.g. "CH-FR") - Swiss residents making an outbound trip abroad
    (generate_outbound_flows), as opposed to the large majority of the
    "crossborder" subpopulation (e.g. "FR-CH-FR") who are foreign residents
    commuting into Switzerland."""
    df = pd.read_csv(
        persons_path, sep=";", usecols=["person", "subpopulation", "crossBorderOD"],
        dtype={"person": str}, low_memory=False,
    )
    is_swiss_resident = df.subpopulation.eq("crossborder") & df.crossBorderOD.str.startswith("CH", na=False)
    return set(df.loc[is_swiss_resident, "person"])


# ---------------------------------------------------------------------------
# Streaming events parsing
# ---------------------------------------------------------------------------

def count_car_link_entries(events_path, cross_border_ids, swiss_resident_ids):
    """Single streaming pass over the events file. Returns three Counters
    keyed by (link_id, hour): all car link entries, the subset made by
    cross-border agents, and the further subset made by the Swiss-resident
    cross-border agents (swiss_resident_ids is a subset of cross_border_ids,
    so swiss_resident_counts <= crossborder_counts at every key)."""

    total_counts = Counter()
    crossborder_counts = Counter()
    swiss_resident_counts = Counter()

    processed = 0
    with xopen.xopen(events_path, "r") as f:
        parser = ET.iterparse(f, events=["start", "end"])
        _, root = next(parser)  # <events> start tag, kept to periodically release finished events

        for event, elem in parser:
            if event != "end" or elem.tag != "event":
                continue

            processed += 1
            if processed % PROGRESS_EVERY == 0:
                logger.info("Processed %d events...", processed)

            if elem.attrib.get("type") in LINK_ENTRY_EVENT_TYPES:
                vehicle = elem.attrib.get("vehicle", "")
                if vehicle.endswith(CAR_VEHICLE_SUFFIX):
                    link_id = elem.attrib["link"]
                    hour = int(float(elem.attrib["time"]) // 3600) % 24
                    key = (link_id, hour)

                    total_counts[key] += 1

                    person_id = vehicle[: -len(CAR_VEHICLE_SUFFIX)]
                    if person_id in cross_border_ids:
                        crossborder_counts[key] += 1
                        if person_id in swiss_resident_ids:
                            swiss_resident_counts[key] += 1

            elem.clear()
            if processed % PROGRESS_EVERY == 0:
                root.clear()

    logger.info("Finished streaming %d events from %s", processed, events_path)
    return total_counts, crossborder_counts, swiss_resident_counts


# ---------------------------------------------------------------------------
# Aggregation
# ---------------------------------------------------------------------------

def build_hourly_dataframe(total_counts, crossborder_counts, swiss_resident_counts):
    rows = [
        dict(
            link_id=link_id, hour=hour, total_flow=count,
            crossborder_flow=crossborder_counts.get((link_id, hour), 0),
            swiss_resident_flow=swiss_resident_counts.get((link_id, hour), 0),
        )
        for (link_id, hour), count in total_counts.items()
    ]
    df = pd.DataFrame(rows, columns=["link_id", "hour", "total_flow", "crossborder_flow", "swiss_resident_flow"])
    return df.sort_values(["link_id", "hour"]).reset_index(drop=True)


def aggregate_daily(df_hourly):
    df_daily = df_hourly.groupby("link_id", as_index=False)[
        ["total_flow", "crossborder_flow", "swiss_resident_flow"]
    ].sum()
    df_daily["crossborder_share_pct"] = np.where(
        df_daily.total_flow > 0, 100.0 * df_daily.crossborder_flow / df_daily.total_flow, np.nan
    )
    # Share of Swiss residents AMONG cross-border car users on this link (not
    # among all traffic) - so it's only meaningful, and only defined, where
    # crossborder_flow > 0.
    df_daily["swiss_resident_share_pct"] = np.where(
        df_daily.crossborder_flow > 0, 100.0 * df_daily.swiss_resident_flow / df_daily.crossborder_flow, np.nan
    )
    return df_daily.sort_values("total_flow", ascending=False).reset_index(drop=True)


def attach_road_attributes(df_daily, network):
    links = network.links[["link_id", "highway", "permlanes"]].copy()
    links["link_id"] = links["link_id"].astype(str)
    df_daily = df_daily.copy()
    df_daily["link_id"] = df_daily["link_id"].astype(str)
    return df_daily.merge(links, on="link_id", how="left")


# ---------------------------------------------------------------------------
# Plots
# ---------------------------------------------------------------------------

def plot_share_by_road_type(df_daily, output_path):
    df = df_daily[df_daily.highway.notna()].copy()
    if df.empty:
        logger.info("No links with highway information; skipping road-type bar chart.")
        return

    df_avg = df.groupby("highway", as_index=False).agg(
        total_flow=("total_flow", "mean"),
        crossborder_flow=("crossborder_flow", "mean"),
        n_links=("link_id", "nunique"),
    )
    df_avg["crossborder_share_pct"] = 100.0 * df_avg.crossborder_flow / df_avg.total_flow
    df_avg = df_avg.sort_values("total_flow", ascending=False).reset_index(drop=True)

    fig, ax = plt.subplots(figsize=(12, 6))
    x = np.arange(len(df_avg))
    width = 0.38

    ax.bar(x - width / 2, df_avg.total_flow, width, label="Total flow", color="#4c72b0")
    ax.bar(x + width / 2, df_avg.crossborder_flow, width, label="Cross-border flow", color="#dd8452")

    for i, row in df_avg.iterrows():
        ax.text(
            i, max(row.total_flow, row.crossborder_flow) * 1.02,
            f"{row.crossborder_share_pct:.0f}% (n={row.n_links})",
            ha="center", va="bottom", fontsize=9, fontweight="bold",
        )

    ax.set_xticks(x)
    ax.set_xticklabels(df_avg.highway, rotation=30, ha="right")
    ax.set_ylabel("Average daily flow per link (vehicles/day)")
    ax.set_title("Average Link Flow by Road Type: Total vs. Cross-Border Agents")
    ax.legend()
    ax.grid(True, axis="y", linestyle="--", alpha=0.4)
    plt.tight_layout()

    output_file = os.path.join(output_path, "cross_border_share_by_road_type.png")
    plt.savefig(output_file, dpi=150, bbox_inches="tight")
    plt.close()
    logger.info("Saved road-type breakdown to %s", output_file)


def plot_share_map(df_daily, network, output_path):
    geometry = network.get_ways(road_types=ROAD_TYPES_FOR_MAP)
    if geometry.empty:
        logger.info("No major-road geometry available; skipping cross-border share map.")
        return

    geometry = geometry.copy()
    geometry["link_id"] = geometry["link_id"].astype(str)

    merged = geometry.merge(df_daily[["link_id", "total_flow", "crossborder_share_pct"]], on="link_id", how="inner")
    if merged.empty:
        logger.info("No major-road links have cross-border flow data; skipping map.")
        return

    fig, ax = plt.subplots(figsize=(12, 10))
    geometry.plot(ax=ax, color="#dddddd", linewidth=0.5, zorder=1)

    merged = gpd.GeoDataFrame(merged, geometry="geometry", crs=geometry.crs)
    merged.plot(
        ax=ax, column="crossborder_share_pct", cmap="inferno_r",
        linewidth=merged.total_flow.clip(upper=merged.total_flow.quantile(0.95)) / merged.total_flow.max() * 3 + 0.5,
        legend=True, legend_kwds={"label": "Cross-border share of daily flow (%)", "shrink": 0.6},
        zorder=2,
    )

    ax.set_title("Simulated Cross-Border Share of Traffic on Major Roads")
    ax.set_axis_off()
    plt.tight_layout()

    output_file = os.path.join(output_path, "cross_border_share_map.png")
    plt.savefig(output_file, dpi=200, bbox_inches="tight")
    plt.close()
    logger.info("Saved cross-border share map to %s", output_file)


def plot_crossborder_flow_map(df_daily, network, extent_path, swiss_border, output_path):

    if not extent_path:
        logger.info("extent_path is not configured; skipping cross-border flow map.")
        return
    if not os.path.exists(extent_path):
        logger.warning("extent_path %s does not exist; skipping cross-border flow map.", extent_path)
        return

    boundary = gpd.read_file(extent_path)

    # Deliberately not network.get_geometry(): when export_detailed_network
    # is enabled that returns the pt2matsim detailed-geometry CSV, whose
    # link_id is the pre-simplification/pre-merge id, not the simulation
    # link_id that output_events (and therefore crossborder_flow) is keyed
    # by. The interior Swiss network goes through that simplification and
    # so silently fails to join there, while cross-border links added later
    # never got simplified and happen to join correctly - which is exactly
    # why only the cross-border side of the extent showed flow before this
    # fix. Passing an empty geometry_file forces straight node-to-node link
    # geometry, built from the same link table the flow counts use, so the
    # join is correct everywhere.
    geometry = network.read_network_geometry(file_path="").copy()
    geometry["link_id"] = geometry["link_id"].astype(str)

    if boundary.crs != geometry.crs:
        boundary = boundary.to_crs(geometry.crs)
    # MMT_extent_cleaned.gpkg carries a Z coordinate (e.g. an elevation value
    # on every vertex); force_2d drops it so this polygon and the swiss_border
    # one below (from swissBOUNDARIES3D, 3D by construction) don't end up
    # mixing 3D and 2D geometry with the flat 2D flow-line data on the same
    # map, which is what was actually breaking the render.
    region = shapely.force_2d(unary_union(boundary.geometry))

    # The extent only cuts off the Swiss side; the French side is shown as
    # far as the network actually extends. So a link is kept if it's inside
    # the extent OR it isn't in Switzerland at all - only interior-CH links
    # beyond the extent get dropped.
    swiss_border_full = shapely.force_2d(unary_union(gpd.GeoSeries(swiss_border).to_crs(geometry.crs)))

    # replicate_of is set on the bookkeeping rows replicate_merged_links()
    # adds for original sub-segment ids absorbed into a simplified simulation
    # link (kept so count stations can be matched to the right original
    # geometry elsewhere) - they share their base link's from/to node, so our
    # node-to-node geometry would otherwise draw them as an exact duplicate
    # of the real link, permanently stuck at 0 flow since they're never the
    # id actually used in output_events.
    links = network.links[["link_id", "freespeed", "replicate_of"]].copy()
    links["link_id"] = links["link_id"].astype(str)
    links = links[links["replicate_of"].isna()]
    fast_link_ids = set(links.loc[links.freespeed >= MIN_SPEED_KMH_FOR_FLOW_MAP / 3.6, "link_id"])

    keep_mask = geometry.link_id.isin(fast_link_ids) & (
        geometry.intersects(region) | ~geometry.intersects(swiss_border_full)
    )
    geometry = geometry[keep_mask]
    if geometry.empty:
        logger.info(
            "No roads with freespeed >= %d km/h found inside the scenario extent; skipping cross-border flow map.",
            MIN_SPEED_KMH_FOR_FLOW_MAP,
        )
        return

    merged = geometry.merge(
        df_daily[["link_id", "crossborder_flow", "swiss_resident_share_pct"]], on="link_id", how="left",
    )
    merged["crossborder_flow"] = merged["crossborder_flow"].fillna(0.0)
    merged = gpd.GeoDataFrame(merged, geometry="geometry", crs=geometry.crs)

    if not (merged.crossborder_flow > 0).any():
        logger.info("No cross-border flow recorded on qualifying roads inside the scenario extent; skipping map.")
        return

    path_data = Plotter._prepare_path_data(
        merged.to_crs(epsg=4326), ["link_id", "crossborder_flow", "swiss_resident_share_pct"],
    )
    path_data["_tooltip_html"] = path_data.apply(
        lambda row: Plotter._build_tooltip_html(row, ["link_id", "crossborder_flow", "swiss_resident_share_pct"]),
        axis=1,
    )

    # Color and width both track crossborder_flow, clipped at the 98th
    # percentile so a handful of very high-flow links don't wash out the
    # rest of the color scale. A single-hue gray-to-dark-blue ramp (rather
    # than a multi-hue colormap like viridis/inferno) reads correctly for
    # colorblind viewers, and doubles as a natural extension of the gray
    # used for zero-flow links. The normalization uses a square root so the
    # many moderate-flow interior links - spread across a much denser
    # network than the few high-volume border corridors - don't get
    # compressed into a barely-different shade near the gray end.
    max_flow = max(path_data.loc[path_data.crossborder_flow > 0, "crossborder_flow"].quantile(0.98), 1.0)

    def color_for(flow):
        if flow <= 0:
            return [*_FLOW_COLOR_LOW, 60]
        normalized = (min(flow, max_flow) / max_flow) ** 0.5
        return [*_gray_to_blue(normalized), _flow_alpha(normalized)]

    path_data["color"] = path_data["crossborder_flow"].apply(color_for)
    # Wider than a typical basemap road line, and scaled up further with flow,
    # so the colored flow links read clearly over the grayscale basemap.
    path_data["width"] = np.where(
        path_data.crossborder_flow > 0,
        (path_data.crossborder_flow.clip(upper=max_flow) / max_flow) ** 0.5 * 16 + 3,
        1.0,
    )

    # Share of Swiss residents among cross-border car users on this link:
    # gray-to-orange (orange/blue is a colorblind-safe pair, distinct from
    # the blue flow-magnitude ramp above) so the two metrics aren't
    # confusable when switching between them. Width still tracks flow
    # magnitude (not the share itself), so this layer answers "of the
    # traffic already shown, what fraction is Swiss residents" rather than
    # introducing an unrelated size encoding. NaN (no cross-border flow on
    # this link at all, so the share is undefined) gets the same neutral
    # gray as a 0%-flow link. The scale saturates at SHARE_COLOR_SATURATION_PCT
    # rather than 100%, since Swiss residents are a small minority of
    # cross-border car users overall (most links never reach high shares) -
    # linearly stretching to 100% would leave nearly everything a barely
    # distinguishable pale gray; any link at or above that threshold gets
    # the darkest color instead.
    def share_color_for(share):
        if pd.isna(share):
            return [*_FLOW_COLOR_LOW, 60]
        normalized = min(share, SHARE_COLOR_SATURATION_PCT) / SHARE_COLOR_SATURATION_PCT
        return [*_gray_to_orange(normalized), _flow_alpha(normalized)]

    path_data["share_color"] = path_data["swiss_resident_share_pct"].apply(share_color_for)

    # A single PathLayer with this many rows (100k+ for a Switzerland-sized
    # extent) can silently render incompletely in the browser - deck.gl/WebGL
    # attribute buffers have practical size limits, and large layers can drop
    # or corrupt part of the geometry without any visible error. Verified
    # against this exact data that the underlying values were all correct
    # (colors/widths/positions), so the fix is to split the layer into
    # chunks small enough to render reliably, not to touch the data itself.
    FLOW_LAYER_CHUNK_SIZE = 20_000
    flow_layers = [
        pdk.Layer(
            "PathLayer",
            chunk,
            id=f"crossborder-flow-{start}",
            pickable=True,
            auto_highlight=True,
            get_path="path",
            get_width="width",
            get_color="color",
            highlight_color=[0, 200, 255],
            # A hard pixel floor, not just a meters-scaled width: interior
            # Swiss links are individually much shorter than France's long,
            # unbroken motorway/trunk segments (dense intersections vs. long
            # highway stretches), so at country-scale zoom even a correctly
            # colored minimum-width segment covers too few pixels to
            # register visually. This keeps every segment visible as a
            # solid mark regardless of its real-world length or zoom level.
            width_min_pixels=3,
            width_scale=3,
        )
        for start in range(0, len(path_data), FLOW_LAYER_CHUNK_SIZE)
        for chunk in [path_data.iloc[start:start + FLOW_LAYER_CHUNK_SIZE]]
    ]

    # Same chunking, same width, different color column - toggled against
    # flow_layers by the "swiss-share-toggle" checkbox injected below.
    # Hidden by default so the map opens on the primary flow-magnitude view.
    share_layers = [
        pdk.Layer(
            "PathLayer",
            chunk,
            id=f"crossborder-share-{start}",
            visible=False,
            pickable=True,
            auto_highlight=True,
            get_path="path",
            get_width="width",
            get_color="share_color",
            highlight_color=[0, 200, 255],
            width_min_pixels=3,
            width_scale=3,
        )
        for start in range(0, len(path_data), FLOW_LAYER_CHUNK_SIZE)
        for chunk in [path_data.iloc[start:start + FLOW_LAYER_CHUNK_SIZE]]
    ]

    extent_layer = _polygon_outline_layer(region, geometry.crs, color=[0, 0, 0], width=2)
    # Only the part of the national border that actually runs through the
    # extent is relevant here; the rest of the country outline is just noise.
    # (swiss_border_full itself was already computed above, for the France-
    # side link filter.)
    swiss_border_geometry = swiss_border_full.intersection(region)
    swiss_border_layer = (
        _polygon_outline_layer(swiss_border_geometry, geometry.crs, color=[178, 24, 43], width=1.5)
        if not swiss_border_geometry.is_empty
        else None
    )

    # Fit the view to the extent boundary itself, not the mean of every link
    # vertex: qualifying links are denser outside Switzerland than inside it,
    # so an unweighted vertex average pulls the camera toward the French side
    # and (at a fixed zoom) crops the Swiss portion out of the initial view.
    # A small margin keeps the extent from sitting flush against the window
    # edge; compute_view's zoom formula assumes a square viewport, so no
    # further manual zoom-out is applied on top of that.
    extent_bounds_ll = gpd.GeoSeries([region], crs=geometry.crs).to_crs(epsg=4326).total_bounds
    minx, miny, maxx, maxy = extent_bounds_ll
    margin_x, margin_y = (maxx - minx) * 0.05, (maxy - miny) * 0.05
    view_state = compute_view([
        [minx - margin_x, miny - margin_y],
        [maxx + margin_x, maxy + margin_y],
    ])
    view_state.pitch = 0
    tooltip = {
        "html": "{_tooltip_html}",
        "style": {"color": "white", "background-color": "black", "padding": "10px"},
    }

    deck = pdk.Deck(
        layers             = [
            l for l in [swiss_border_layer, extent_layer, *flow_layers, *share_layers] if l is not None
        ],
        initial_view_state = view_state,
        tooltip            = tooltip,
        map_style          = "https://basemaps.cartocdn.com/gl/positron-gl-style/style.json",
    )

    output_file = os.path.join(output_path, "cross_border_flow_map.html")
    deck.to_html(output_file, notebook_display=False)
    _inject_flow_color_legend(output_file, "Cross-border agent flow (vehicles/day)", max_flow, gamma=0.5)
    logger.info("Saved cross-border flow map to %s", output_file)



_FLOW_COLOR_LOW = (225, 225, 225)
_FLOW_COLOR_HIGH = (8, 29, 225)


def _gray_to_blue(t):
    t = max(0.0, min(1.0, t))
    return [int(_FLOW_COLOR_LOW[i] + (_FLOW_COLOR_HIGH[i] - _FLOW_COLOR_LOW[i]) * t) for i in range(3)]


_SHARE_COLOR_LOW = (225, 225, 225)
_SHARE_COLOR_HIGH = (230, 85, 13)


def _gray_to_orange(t):
    t = max(0.0, min(1.0, t))
    return [int(_SHARE_COLOR_LOW[i] + (_SHARE_COLOR_HIGH[i] - _SHARE_COLOR_LOW[i]) * t) for i in range(3)]


def _flow_alpha(t, low=80, high=255):
    t = max(0.0, min(1.0, t))
    return int(low + (high - low) * t)


def _polygon_outline_layer(geometry, crs, color, width):
    """A stroke-only PolygonLayer for a (Multi)Polygon boundary. Also handles
    a GeometryCollection, e.g. from intersecting a border with an extent
    polygon can leave slivers of LineString/Point alongside the real
    Polygon parts - those non-polygon slivers are dropped since they have no
    exterior to outline."""

    if geometry.geom_type in ("MultiPolygon", "GeometryCollection"):
        parts = [part for part in geometry.geoms if part.geom_type == "Polygon"]
    else:
        parts = [geometry]
    gdf = gpd.GeoDataFrame(geometry=parts, crs=crs).to_crs(epsg=4326)
    gdf["coordinates"] = gdf.geometry.exterior.apply(lambda x: list(x.coords))
    return pdk.Layer(
        "PolygonLayer",
        gdf,
        get_polygon="coordinates",
        get_fill_color=[0, 0, 0, 0],
        stroked=True,
        get_line_color=color,
        line_width_min_pixels=width,
        pickable=False,
    )


def _flow_color_stops(gamma):
    return ", ".join(
        f"rgba({_gray_to_blue(t ** gamma)[0]},{_gray_to_blue(t ** gamma)[1]},{_gray_to_blue(t ** gamma)[2]},"
        f"{_flow_alpha(t ** gamma) / 255:.2f}) {t * 100:.0f}%"
        for t in np.linspace(0, 1, 6)
    )


def _share_color_stops():
    return ", ".join(
        f"rgba({_gray_to_orange(t)[0]},{_gray_to_orange(t)[1]},{_gray_to_orange(t)[2]},"
        f"{_flow_alpha(t) / 255:.2f}) {t * 100:.0f}%"
        for t in np.linspace(0, 1, 6)
    )


def _inject_flow_color_legend(path_to_save, flow_label, flow_max, gamma=1.0):
    """Add a legend to a saved pydeck HTML map, plus a checkbox that toggles
    between the flow-magnitude layers ("crossborder-flow-*") and the
    Swiss-resident-share layers ("crossborder-share-*") built alongside them
    in plot_crossborder_flow_map, swapping the visible gradient/legend text
    to match. pydeck has no built-in legend or layer-visibility control, and
    Plotter._inject_flow_metric_controls is wired to the "counts-points-*"
    scatterplot layers used elsewhere (a color-accessor swap on one layer),
    not this two-layer-set visibility swap, so this is a separate, simpler
    mechanism. gamma must match the exponent used in color_for so the flow
    gradient reflects what's really on the map, not a plain linear scale."""

    flow_stops = _flow_color_stops(gamma)
    share_stops = _share_color_stops()

    legend_html = f"""
<div id="crossborder-legend" style="position:absolute;z-index:20;bottom:12px;left:12px;padding:10px 12px;
            border-radius:7px;background:rgba(255,255,255,0.95);
            box-shadow:0 2px 10px rgba(0,0,0,0.28);color:#222;
            font:12px/1.3 Arial, sans-serif;">
  <label style="display:flex;align-items:center;gap:6px;margin-bottom:8px;cursor:pointer;">
    <input id="crossborder-share-toggle" type="checkbox">
    Show share of Swiss residents instead
  </label>
  <div id="crossborder-legend-title" style="font-weight:700;margin-bottom:6px;">{escape(flow_label)}</div>
  <div id="crossborder-legend-bar" style="width:180px;height:12px;border:1px solid #777;
              background:linear-gradient(to right, {flow_stops});"></div>
  <div style="display:flex;justify-content:space-between;margin-top:3px;">
    <span>0</span><span id="crossborder-legend-max">{flow_max:.0f}+</span>
  </div>
  <div id="crossborder-legend-note" style="margin-top:4px;color:#777;">Gray link = no measured cross-border flow</div>
  <div style="margin-top:2px;color:#b2182b;">Red outline = Swiss national border</div>
  <div style="color:#222;">Black outline = scenario extent</div>
</div>
"""
    script = f"""
<script>
(function () {{
  const flowStops = {json.dumps(flow_stops)};
  const shareStops = {json.dumps(share_stops)};
  const flowLabel = {json.dumps(flow_label)};
  const flowMax = {json.dumps(f"{flow_max:.0f}+")};
  const shareMax = {json.dumps(f"{SHARE_COLOR_SATURATION_PCT:.0f}%+")};
  const flowNote = "Gray link = no measured cross-border flow";
  const shareNote = "Share of Swiss residents among cross-border car users on this link (capped at " +
    {json.dumps(f"{SHARE_COLOR_SATURATION_PCT:.0f}%")} + "); gray = no cross-border flow here";

  const checkbox = document.getElementById("crossborder-share-toggle");
  const title = document.getElementById("crossborder-legend-title");
  const bar = document.getElementById("crossborder-legend-bar");
  const maxLabel = document.getElementById("crossborder-legend-max");
  const note = document.getElementById("crossborder-legend-note");
  const deck = typeof deckInstance === "undefined" ? null : deckInstance;

  checkbox.addEventListener("change", function () {{
    const showShare = checkbox.checked;
    title.textContent = showShare ? "Share of Swiss residents (%)" : flowLabel;
    bar.style.background = "linear-gradient(to right, " + (showShare ? shareStops : flowStops) + ")";
    maxLabel.textContent = showShare ? shareMax : flowMax;
    note.textContent = showShare ? shareNote : flowNote;

    if (!deck || !deck.props || !deck.props.layers) {{
      return;
    }}
    const layers = deck.props.layers.map(function (layer) {{
      if (layer.id.startsWith("crossborder-flow-")) {{
        return layer.clone({{visible: !showShare}});
      }}
      if (layer.id.startsWith("crossborder-share-")) {{
        return layer.clone({{visible: showShare}});
      }}
      return layer;
    }});
    deck.setProps({{layers: layers}});
  }});
}})();
</script>
"""
    path = Path(path_to_save)
    html = path.read_text(encoding="utf-8")
    html = html.replace("</body>", legend_html + "\n</body>", 1)
    html = html.replace("</html>", script + "\n</html>", 1)
    path.write_text(html, encoding="utf-8")
