"""
Stage: analysis.counts.cross_border_flow

Per-link car flow generated by cross-border agents (subpopulation ==
"crossborder"), computed from output_events.xml.gz since MATSim's own flow
outputs aggregate every vehicle and can't be split by agent. Counts are
rescaled by 1 / input_downsampling and cover car mode only, so they're
comparable to but not identical to simulated_flow elsewhere (that includes
car_passenger/trucks unless counts.filterModes is set).

Writes cross_border_link_flow_{daily,hourly}.csv and two plots into the
shared get_analysis_output_path folder (same as every other analysis.counts
stage).
"""

import glob
import logging
import os
from collections import Counter

import geopandas as gpd
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import pydeck as pdk
import shapely
import xml.etree.ElementTree as ET
import xopen
from pydeck.data_utils.viewport_helpers import compute_view
from shapely.ops import unary_union

from .flow_metrics import add_metric_columns, inject_metric_dropdown_legend, share_column
from .matching.plots import Plotter
from .paths import configure_simulation_path, get_analysis_output_path, get_simulation_path

logger = logging.getLogger("synpp")

CAR_VEHICLE_SUFFIX = ":car"
LINK_ENTRY_EVENT_TYPES = {"entered link"}
ROAD_TYPES_FOR_MAP = ["motorway", "trunk", "primary", "motorway_link", "trunk_link", "primary_link"]
PROGRESS_EVERY = 2_000_000
MIN_SPEED_KMH_FOR_FLOW_MAP = 50

# Rider-group flow columns produced by count_car_link_entries /
# build_hourly_dataframe, on top of total_flow. "crossborder_flow" is
# non-Swiss cross-border residents only (foreign commuters/travelers) -
# Swiss residents crossing the border for an activity get their own
# swiss_crossborder_flow instead, so the two never overlap (see execute).
# Each column gets a matching "<name>_share_pct" column (flow_metrics.share_column)
# and a pair of METRICS entries - mirrors cross_border_flow_pt.py's layer set.
RIDER_GROUP_FLOW_COLUMNS = ["crossborder_flow", "swiss_crossborder_flow", "french_flow"]


def configure(context):
    context.stage("analysis.counts.matching.network")
    context.stage("data.spatial.swiss_border")
    configure_simulation_path(context)
    context.config("only_weekday", default=False)
    context.config("input_downsampling")
    context.config("cross_border_flow_min_daily_count", default=20)
    context.config("extent_path", default="")


def execute(context):
    simulation_path = get_simulation_path(context)
    output_path = get_analysis_output_path(context)
    os.makedirs(output_path, exist_ok=True)

    persons_path = _find_output_file(simulation_path, "output_persons.csv.gz")
    events_path = _find_output_file(simulation_path, "output_events.xml.gz")

    cross_border_ids = load_cross_border_person_ids(persons_path)
    swiss_crossborder_ids = load_swiss_resident_cross_border_person_ids(persons_path)
    french_resident_ids = load_french_resident_cross_border_person_ids(persons_path)
    foreign_crossborder_ids = cross_border_ids - swiss_crossborder_ids
    logger.info(
        "Found %d cross-border persons (%d Swiss-resident, %d France-resident) in %s",
        len(cross_border_ids), len(swiss_crossborder_ids), len(french_resident_ids), persons_path,
    )

    rider_group_ids = {
        "crossborder_flow": foreign_crossborder_ids,
        "swiss_crossborder_flow": swiss_crossborder_ids,
        "french_flow": french_resident_ids,
    }
    total_counts, group_counts = count_car_link_entries(events_path, rider_group_ids)
    logger.info("Counted car entries on %d distinct links", len(total_counts))

    df_hourly = build_hourly_dataframe(total_counts, group_counts)

    sample_size = context.config("input_downsampling")
    for column in ["total_flow", *RIDER_GROUP_FLOW_COLUMNS]:
        df_hourly[column] = df_hourly[column] / sample_size

    df_daily = aggregate_daily(df_hourly)

    network = context.stage("analysis.counts.matching.network")
    df_daily = attach_road_attributes(df_daily, network)

    hourly_csv = os.path.join(output_path, "cross_border_link_flow_hourly.csv")
    daily_csv = os.path.join(output_path, "cross_border_link_flow_daily.csv")
    #df_hourly.to_csv(hourly_csv, index=False)
    #df_daily.to_csv(daily_csv, index=False)
    #logger.info("Saved per-link cross-border flow to %s and %s", daily_csv, hourly_csv)

    min_daily_count = context.config("cross_border_flow_min_daily_count")
    df_plot = df_daily[df_daily.total_flow >= min_daily_count].copy()

    #plot_share_by_road_type(df_plot, output_path)
    #plot_share_map(df_plot, network, output_path)
    swiss_border = context.stage("data.spatial.swiss_border")
    plot_crossborder_flow_map(
        df_plot, network, context.config("extent_path"), swiss_border, output_path,
    )

    return dict(done=True, path=output_path, daily_csv=daily_csv, hourly_csv=hourly_csv)


# ---------------------------------------------------------------------------
# File discovery
# ---------------------------------------------------------------------------

def _find_output_file(simulation_path, filename):
    """MATSim writes these directly under simulation_output; fall back to the
    last ITERS snapshot if the final output is missing (unfinished run)."""

    direct_path = os.path.join(simulation_path, filename)
    if os.path.exists(direct_path):
        return direct_path

    stem, _, suffix = filename.partition(".")
    candidates = glob.glob(os.path.join(simulation_path, "ITERS", "*", f"*.{suffix}"))
    if not candidates:
        raise FileNotFoundError(f"Could not find {filename} in {simulation_path} (or its ITERS folder)")

    candidate = max(candidates, key=os.path.getmtime)
    logger.warning("%s not found at %s, using latest iteration snapshot %s instead", filename, direct_path, candidate)
    return candidate


# ---------------------------------------------------------------------------
# Cross-border person identification
# ---------------------------------------------------------------------------

def load_cross_border_person_ids(persons_path):
    # low_memory=False: the default chunked C-engine read hits a pandas bug
    # (IndexError in _concatenate_chunks) on this file size with usecols set.
    df = pd.read_csv(
        persons_path, sep=";", usecols=["person", "subpopulation"], dtype={"person": str}, low_memory=False,
    )
    return set(df.loc[df.subpopulation == "crossborder", "person"])


def load_swiss_resident_cross_border_person_ids(persons_path):
    """The subset of cross-border persons whose crossBorderOD starts with
    "CH" (e.g. "CH-FR") - Swiss residents making an outbound trip abroad
    (generate_outbound_flows), as opposed to the large majority of the
    "crossborder" subpopulation (e.g. "FR-CH-FR") who are foreign residents
    commuting into Switzerland."""
    df = pd.read_csv(
        persons_path, sep=";", usecols=["person", "subpopulation", "crossBorderOD"],
        dtype={"person": str}, low_memory=False,
    )
    is_swiss_resident = df.subpopulation.eq("crossborder") & df.crossBorderOD.str.startswith("CH", na=False)
    return set(df.loc[is_swiss_resident, "person"])


def load_french_resident_cross_border_person_ids(persons_path):
    """The subset of cross-border persons whose crossBorderOD starts with
    "FR-CH" (e.g. "FR-CH-FR", "FR-CH-DE") - agents resident in France
    commuting/traveling into Switzerland, as opposed to Swiss residents
    making an outbound trip there (load_swiss_resident_cross_border_person_ids)
    or residents of the other neighboring countries (DE/IT/AT/LI)."""
    df = pd.read_csv(
        persons_path, sep=";", usecols=["person", "subpopulation", "crossBorderOD"],
        dtype={"person": str}, low_memory=False,
    )
    is_french_resident = df.subpopulation.eq("crossborder") & df.crossBorderOD.str.startswith("FR-CH", na=False)
    return set(df.loc[is_french_resident, "person"])


# ---------------------------------------------------------------------------
# Streaming events parsing
# ---------------------------------------------------------------------------

def count_car_link_entries(events_path, rider_group_ids):
    """Single streaming pass over the events file. rider_group_ids:
    {flow_column_name: set_of_person_ids} - e.g. RIDER_GROUP_FLOW_COLUMNS
    mapped to their id sets (mutually exclusive person sets in practice, but
    this doesn't assume that). Returns total_counts and {flow_column_name:
    Counter} (one per rider_group_ids entry), each keyed by (link_id, hour)."""

    total_counts = Counter()
    group_counts = {group: Counter() for group in rider_group_ids}

    processed = 0
    with xopen.xopen(events_path, "r") as f:
        parser = ET.iterparse(f, events=["start", "end"])
        _, root = next(parser)  # <events> start tag, kept to periodically release finished events

        for event, elem in parser:
            if event != "end" or elem.tag != "event":
                continue

            processed += 1
            if processed % PROGRESS_EVERY == 0:
                logger.info("Processed %d events...", processed)

            if elem.attrib.get("type") in LINK_ENTRY_EVENT_TYPES:
                vehicle = elem.attrib.get("vehicle", "")
                if vehicle.endswith(CAR_VEHICLE_SUFFIX):
                    link_id = elem.attrib["link"]
                    hour = int(float(elem.attrib["time"]) // 3600) % 24
                    key = (link_id, hour)

                    total_counts[key] += 1

                    person_id = vehicle[: -len(CAR_VEHICLE_SUFFIX)]
                    for group, ids in rider_group_ids.items():
                        if person_id in ids:
                            group_counts[group][key] += 1

            elem.clear()
            if processed % PROGRESS_EVERY == 0:
                root.clear()

    logger.info("Finished streaming %d events from %s", processed, events_path)
    return total_counts, group_counts


# ---------------------------------------------------------------------------
# Aggregation
# ---------------------------------------------------------------------------

def build_hourly_dataframe(total_counts, group_counts):
    rows = [
        dict(
            link_id=link_id, hour=hour, total_flow=count,
            **{group: counts.get((link_id, hour), 0) for group, counts in group_counts.items()},
        )
        for (link_id, hour), count in total_counts.items()
    ]
    df = pd.DataFrame(rows, columns=["link_id", "hour", "total_flow", *RIDER_GROUP_FLOW_COLUMNS])
    return df.sort_values(["link_id", "hour"]).reset_index(drop=True)


def aggregate_daily(df_hourly):
    df_daily = df_hourly.groupby("link_id", as_index=False)[
        ["total_flow", *RIDER_GROUP_FLOW_COLUMNS]
    ].sum()
    # Share of each rider group AMONG ALL traffic on this link (matches
    # cross_border_flow_pt.py's convention) - not among cross-border users
    # only, as an earlier version of this had it for swiss_resident_share_pct.
    for column in RIDER_GROUP_FLOW_COLUMNS:
        df_daily[share_column(column)] = np.where(
            df_daily.total_flow > 0, 100.0 * df_daily[column] / df_daily.total_flow, np.nan
        )
    return df_daily.sort_values("total_flow", ascending=False).reset_index(drop=True)


def attach_road_attributes(df_daily, network):
    links = network.links[["link_id", "highway", "permlanes"]].copy()
    links["link_id"] = links["link_id"].astype(str)
    df_daily = df_daily.copy()
    df_daily["link_id"] = df_daily["link_id"].astype(str)
    return df_daily.merge(links, on="link_id", how="left")


# ---------------------------------------------------------------------------
# Plots
# ---------------------------------------------------------------------------

def plot_share_by_road_type(df_daily, output_path):
    df = df_daily[df_daily.highway.notna()].copy()
    if df.empty:
        logger.info("No links with highway information; skipping road-type bar chart.")
        return

    df_avg = df.groupby("highway", as_index=False).agg(
        total_flow=("total_flow", "mean"),
        crossborder_flow=("crossborder_flow", "mean"),
        n_links=("link_id", "nunique"),
    )
    df_avg["crossborder_share_pct"] = 100.0 * df_avg.crossborder_flow / df_avg.total_flow
    df_avg = df_avg.sort_values("total_flow", ascending=False).reset_index(drop=True)

    fig, ax = plt.subplots(figsize=(12, 6))
    x = np.arange(len(df_avg))
    width = 0.38

    ax.bar(x - width / 2, df_avg.total_flow, width, label="Total flow", color="#4c72b0")
    ax.bar(x + width / 2, df_avg.crossborder_flow, width, label="Cross-border flow", color="#dd8452")

    for i, row in df_avg.iterrows():
        ax.text(
            i, max(row.total_flow, row.crossborder_flow) * 1.02,
            f"{row.crossborder_share_pct:.0f}% (n={row.n_links})",
            ha="center", va="bottom", fontsize=9, fontweight="bold",
        )

    ax.set_xticks(x)
    ax.set_xticklabels(df_avg.highway, rotation=30, ha="right")
    ax.set_ylabel("Average daily flow per link (vehicles/day)")
    ax.set_title("Average Link Flow by Road Type: Total vs. Cross-Border Agents")
    ax.legend()
    ax.grid(True, axis="y", linestyle="--", alpha=0.4)
    plt.tight_layout()

    output_file = os.path.join(output_path, "cross_border_share_by_road_type.png")
    plt.savefig(output_file, dpi=150, bbox_inches="tight")
    plt.close()
    logger.info("Saved road-type breakdown to %s", output_file)


def plot_share_map(df_daily, network, output_path):
    geometry = network.get_ways(road_types=ROAD_TYPES_FOR_MAP)
    if geometry.empty:
        logger.info("No major-road geometry available; skipping cross-border share map.")
        return

    geometry = geometry.copy()
    geometry["link_id"] = geometry["link_id"].astype(str)

    merged = geometry.merge(df_daily[["link_id", "total_flow", "crossborder_share_pct"]], on="link_id", how="inner")
    if merged.empty:
        logger.info("No major-road links have cross-border flow data; skipping map.")
        return

    fig, ax = plt.subplots(figsize=(12, 10))
    geometry.plot(ax=ax, color="#dddddd", linewidth=0.5, zorder=1)

    merged = gpd.GeoDataFrame(merged, geometry="geometry", crs=geometry.crs)
    merged.plot(
        ax=ax, column="crossborder_share_pct", cmap="inferno_r",
        linewidth=merged.total_flow.clip(upper=merged.total_flow.quantile(0.95)) / merged.total_flow.max() * 3 + 0.5,
        legend=True, legend_kwds={"label": "Cross-border share of daily flow (%)", "shrink": 0.6},
        zorder=2,
    )

    ax.set_title("Simulated Cross-Border Share of Traffic on Major Roads")
    ax.set_axis_off()
    plt.tight_layout()

    output_file = os.path.join(output_path, "cross_border_share_map.png")
    plt.savefig(output_file, dpi=200, bbox_inches="tight")
    plt.close()
    logger.info("Saved cross-border share map to %s", output_file)


# Same set of rider-group layers, keys and colors as cross_border_flow_pt.py's
# METRICS, for visual consistency between the car and PT flow maps.
METRICS = [
    {
        "key": "total_flow", "label": "Total car flow (vehicles/day)",
        "low": (225, 225, 225), "high": (35, 139, 69), "gamma": 0.5, "width_basis": "total_flow",
    },
    {
        "key": "crossborder_flow", "label": "Cross-border car flow (vehicles/day, non-Swiss residents)",
        "low": (225, 225, 225), "high": (8, 29, 225), "gamma": 0.5, "width_basis": "crossborder_flow",
    },
    {
        "key": "crossborder_share_pct", "label": "Cross-border share of car traffic (%, non-Swiss residents)",
        "low": (225, 225, 225), "high": (230, 85, 13), "gamma": 1.0, "width_basis": "total_flow",
    },
    {
        "key": "swiss_crossborder_flow", "label": "Swiss-resident cross-border car flow (vehicles/day)",
        "low": (225, 225, 225), "high": (0, 128, 128), "gamma": 0.5, "width_basis": "swiss_crossborder_flow",
    },
    {
        "key": "swiss_crossborder_share_pct", "label": "Swiss-resident cross-border share of car traffic (%)",
        "low": (225, 225, 225), "high": (166, 86, 40), "gamma": 1.0, "width_basis": "total_flow",
    },
    {
        "key": "french_flow", "label": "France-resident car flow (vehicles/day)",
        "low": (225, 225, 225), "high": (117, 25, 128), "gamma": 0.5, "width_basis": "french_flow",
    },
    {
        "key": "french_share_pct", "label": "France-resident share of car traffic (%)",
        "low": (225, 225, 225), "high": (203, 24, 29), "gamma": 1.0, "width_basis": "total_flow",
    },
]
DEFAULT_METRIC = "crossborder_flow"


def plot_crossborder_flow_map(df_daily, network, extent_path, swiss_border, output_path):

    if not extent_path:
        logger.info("extent_path is not configured; skipping cross-border flow map.")
        return
    if not os.path.exists(extent_path):
        logger.warning("extent_path %s does not exist; skipping cross-border flow map.", extent_path)
        return

    boundary = gpd.read_file(extent_path)

    # Deliberately not network.get_geometry(): when export_detailed_network
    # is enabled that returns the pt2matsim detailed-geometry CSV, whose
    # link_id is the pre-simplification/pre-merge id, not the simulation
    # link_id that output_events (and therefore crossborder_flow) is keyed
    # by. The interior Swiss network goes through that simplification and
    # so silently fails to join there, while cross-border links added later
    # never got simplified and happen to join correctly - which is exactly
    # why only the cross-border side of the extent showed flow before this
    # fix. Passing an empty geometry_file forces straight node-to-node link
    # geometry, built from the same link table the flow counts use, so the
    # join is correct everywhere.
    geometry = network.read_network_geometry(file_path="").copy()
    geometry["link_id"] = geometry["link_id"].astype(str)

    if boundary.crs != geometry.crs:
        boundary = boundary.to_crs(geometry.crs)
    # MMT_extent_cleaned.gpkg carries a Z coordinate (e.g. an elevation value
    # on every vertex); force_2d drops it so this polygon and the swiss_border
    # one below (from swissBOUNDARIES3D, 3D by construction) don't end up
    # mixing 3D and 2D geometry with the flat 2D flow-line data on the same
    # map, which is what was actually breaking the render.
    region = shapely.force_2d(unary_union(boundary.geometry))

    # The extent only cuts off the Swiss side; the French side is shown as
    # far as the network actually extends. So a link is kept if it's inside
    # the extent OR it isn't in Switzerland at all - only interior-CH links
    # beyond the extent get dropped.
    swiss_border_full = shapely.force_2d(unary_union(gpd.GeoSeries(swiss_border).to_crs(geometry.crs)))

    # replicate_of is set on the bookkeeping rows replicate_merged_links()
    # adds for original sub-segment ids absorbed into a simplified simulation
    # link (kept so count stations can be matched to the right original
    # geometry elsewhere) - they share their base link's from/to node, so our
    # node-to-node geometry would otherwise draw them as an exact duplicate
    # of the real link, permanently stuck at 0 flow since they're never the
    # id actually used in output_events.
    links = network.links[["link_id", "freespeed", "replicate_of"]].copy()
    links["link_id"] = links["link_id"].astype(str)
    links = links[links["replicate_of"].isna()]
    fast_link_ids = set(links.loc[links.freespeed >= MIN_SPEED_KMH_FOR_FLOW_MAP / 3.6, "link_id"])

    keep_mask = geometry.link_id.isin(fast_link_ids) & (
        geometry.intersects(region) | ~geometry.intersects(swiss_border_full)
    )
    geometry = geometry[keep_mask]
    if geometry.empty:
        logger.info(
            "No roads with freespeed >= %d km/h found inside the scenario extent; skipping cross-border flow map.",
            MIN_SPEED_KMH_FOR_FLOW_MAP,
        )
        return

    flow_columns = ["total_flow", *RIDER_GROUP_FLOW_COLUMNS]
    share_columns = [share_column(c) for c in RIDER_GROUP_FLOW_COLUMNS]
    merged = geometry.merge(df_daily[["link_id", *flow_columns, *share_columns]], on="link_id", how="left")
    merged[flow_columns] = merged[flow_columns].fillna(0.0)
    merged = gpd.GeoDataFrame(merged, geometry="geometry", crs=geometry.crs)

    # A zero-total_flow link renders as an uninformative gray line either
    # way (every metric's color_for treats <=0 as gray) - dropping it here
    # keeps the map's weight down without losing anything visible. This is
    # the majority of the French-side geometry kept above "as far as the
    # network extends" regardless of whether it carries any recorded flow.
    merged = merged[merged.total_flow > 0].copy()
    if merged.empty:
        logger.info("No flow recorded on qualifying roads inside the scenario extent; skipping map.")
        return

    tooltip_fields = ["link_id", *flow_columns, *share_columns]
    path_data = Plotter._prepare_path_data(merged.to_crs(epsg=4326), tooltip_fields)
    path_data["_tooltip_html"] = path_data.apply(
        lambda row: Plotter._build_tooltip_html(row, tooltip_fields), axis=1,
    )

    # Same METRICS-driven color/width scheme as cross_border_flow_pt.py's
    # map (add_metric_columns), so the two maps' layers read consistently -
    # a single-hue gray-to-color ramp per metric, width tracking that
    # metric's width_basis (its own flow for an absolute layer, total_flow
    # for a share layer), square-root-normalized so moderate-flow interior
    # links don't get compressed into a barely-different shade/width near
    # the low end.
    #
    # Unlike cross_border_flow_pt.py (a few hundred stop-to-stop segments,
    # cheap to just duplicate per metric), this map can have 100k+ link
    # rows - one PathLayer per metric would embed a full independent copy of
    # the path geometry and tooltip HTML into the HTML per metric (7x the
    # data for 7 metrics). Instead every metric's *_color/*_size columns
    # (small numeric columns) are added to the SAME path_data, and a single
    # set of chunked PathLayers is built once; switching the selected metric
    # in the browser just re-clones those layers with a different
    # getColor/getWidth accessor (see inject_metric_dropdown_legend's
    # mode="accessor") rather than toggling visibility across per-metric
    # duplicates. The chunking itself is still needed regardless of metric
    # count: a single PathLayer with this many rows can silently render
    # incompletely in the browser - deck.gl/WebGL attribute buffers have
    # practical size limits.
    metric_maxima = {
        metric["key"]: add_metric_columns(path_data, metric, size_scale=16, size_base=3) for metric in METRICS
    }

    FLOW_LAYER_CHUNK_SIZE = 20_000
    path_layers = [
        pdk.Layer(
            "PathLayer",
            chunk,
            id=f"car-path::{start}",
            pickable=True,
            auto_highlight=True,
            get_path="path",
            get_width=f"{DEFAULT_METRIC}_size",
            get_color=f"{DEFAULT_METRIC}_color",
            highlight_color=[0, 200, 255],
            # A hard pixel floor, not just a meters-scaled width: interior
            # Swiss links are individually much shorter than France's long,
            # unbroken motorway/trunk segments (dense intersections vs. long
            # highway stretches), so at country-scale zoom even a correctly
            # colored minimum-width segment covers too few pixels to
            # register visually. This keeps every segment visible as a
            # solid mark regardless of its real-world length or zoom level.
            width_min_pixels=3,
            width_scale=3,
        )
        for start in range(0, len(path_data), FLOW_LAYER_CHUNK_SIZE)
        for chunk in [path_data.iloc[start:start + FLOW_LAYER_CHUNK_SIZE]]
    ]

    extent_layer = _polygon_outline_layer(region, geometry.crs, color=[0, 0, 0], width=2)
    # Only the part of the national border that actually runs through the
    # extent is relevant here; the rest of the country outline is just noise.
    # (swiss_border_full itself was already computed above, for the France-
    # side link filter.)
    swiss_border_geometry = swiss_border_full.intersection(region)
    swiss_border_layer = (
        _polygon_outline_layer(swiss_border_geometry, geometry.crs, color=[178, 24, 43], width=1.5)
        if not swiss_border_geometry.is_empty
        else None
    )

    # Fit the view to the extent boundary itself, not the mean of every link
    # vertex: qualifying links are denser outside Switzerland than inside it,
    # so an unweighted vertex average pulls the camera toward the French side
    # and (at a fixed zoom) crops the Swiss portion out of the initial view.
    # A small margin keeps the extent from sitting flush against the window
    # edge; compute_view's zoom formula assumes a square viewport, so no
    # further manual zoom-out is applied on top of that.
    extent_bounds_ll = gpd.GeoSeries([region], crs=geometry.crs).to_crs(epsg=4326).total_bounds
    minx, miny, maxx, maxy = extent_bounds_ll
    margin_x, margin_y = (maxx - minx) * 0.05, (maxy - miny) * 0.05
    view_state = compute_view([
        [minx - margin_x, miny - margin_y],
        [maxx + margin_x, maxy + margin_y],
    ])
    view_state.pitch = 0
    tooltip = {
        "html": "{_tooltip_html}",
        "style": {"color": "white", "background-color": "black", "padding": "10px"},
    }

    deck = pdk.Deck(
        layers             = [
            l for l in [swiss_border_layer, extent_layer, *path_layers] if l is not None
        ],
        initial_view_state = view_state,
        tooltip            = tooltip,
        map_style          = "https://basemaps.cartocdn.com/gl/positron-gl-style/style.json",
    )

    output_file = os.path.join(output_path, "cross_border_flow_map.html")
    deck.to_html(output_file, notebook_display=False)
    inject_metric_dropdown_legend(
        output_file, METRICS, metric_maxima, DEFAULT_METRIC,
        layer_prefixes=["car-path::"], dom_id_prefix="car", mode="accessor",
        extra_legend_lines=[
            ("Red outline = Swiss national border", "color:#b2182b;"),
            ("Black outline = scenario extent", "color:#222;"),
        ],
    )
    logger.info("Saved cross-border flow map to %s", output_file)


def _polygon_outline_layer(geometry, crs, color, width):
    """A stroke-only PolygonLayer for a (Multi)Polygon boundary. Also handles
    a GeometryCollection, e.g. from intersecting a border with an extent
    polygon can leave slivers of LineString/Point alongside the real
    Polygon parts - those non-polygon slivers are dropped since they have no
    exterior to outline."""

    if geometry.geom_type in ("MultiPolygon", "GeometryCollection"):
        parts = [part for part in geometry.geoms if part.geom_type == "Polygon"]
    else:
        parts = [geometry]
    gdf = gpd.GeoDataFrame(geometry=parts, crs=crs).to_crs(epsg=4326)
    gdf["coordinates"] = gdf.geometry.exterior.apply(lambda x: list(x.coords))
    return pdk.Layer(
        "PolygonLayer",
        gdf,
        get_polygon="coordinates",
        get_fill_color=[0, 0, 0, 0],
        stroked=True,
        get_line_color=color,
        line_width_min_pixels=width,
        pickable=False,
    )


