import pandas as pd
import geopandas as gpd
import numpy as np
import cma
import pickle
import os
import subprocess

import calibration.pt_routing.calibration_utils as calibration_utils


def define_parameters(random_seed, port_number, canton):

    routing_endpoint = f"http://localhost:{str(port_number)}/router/transit"
    objective        = "distribution_based"

    keep_weekends = False
    keep_workdays = True

    canton_selector = canton

    maximum_batch_size = 4000
    modes_weight       = 1.0
    transfers_weight   = 1.0
    walk_wait_weight   = 0.5
    eval_intermodality = True

    seed       = random_seed
    sigma      = 0.5
    iterations = 2#75 # Number of iterations
    pop_size   = 12 # Number of candidates generated by each iteration of the evolutionary optimization algorithm

    pt_modes      = ["rail", "subway", "ferry", "tram", "funicular", "cable-car", "gondola", "other", "bus"]
    pt_main_modes = ["rail", "tram", "bus", "pt_other"]

    modes_to_main = {
        "rail": "rail",
        "subway": "tram",
        "ferry": "pt_other",
        "tram": "tram",
        "funicular": "pt_other",
        "cable-car": "pt_other",
        "gondola": "pt_other",
        "other": "pt_other",
        "bus": "bus"
    }


    parameters = {
        "routing_endpoint":       routing_endpoint,
        "objective":              objective,
        "maximum_batch_size":     maximum_batch_size,
        "modes_weight":           modes_weight,
        "walk_wait_weight":       walk_wait_weight,
        "transfers_weight":       transfers_weight,
        "evaluate_intermodality": eval_intermodality,
        "seed":                   seed,
        "sigma":                  sigma,
        "popsize":                pop_size,
        "iterations":             iterations,
        "pt_modes":               pt_modes,
        "pt_main_modes":          pt_main_modes,
        "pt_modes_to_main":       modes_to_main,
        "keep_workdays":          keep_workdays,
        "keep_weekends":          keep_weekends,
        "canton_selector":        canton_selector
    }

    return parameters


# Create the variables
# Using values from the Zurich mode choice model, scaled so that rail TT utility is used as a reference fixed to -1.0
# The tram TT utility is absent from the MCM, using rail TT as a reference
def initialize_variables():
    variables = [
        { "name": "rail_u_h", "initial": -1.0, "fixed": True },
        { "name": "bus_u_h", "initial": -1.72 }, 
        { "name": "tram_u_h", "initial": -1.0 },
        { "name": "subway_u_h", "copy": "tram_u_h" },
        { "name": "other_u_h", "copy": "bus_u_h" },
        { "name": "wait_u_h", "initial": -1.72, "fixed": True},
        { "name": "walk_u_h", "initial": -1.97, "fixed": True},
        { "name": "transfer_u", "initial": 0.0, "fixed": True },
        { "name": "raptorPenalties:transfer_intermodal", "initial": 0.39},
        { "name": "raptorPenalties:transfer_rail", "initial": 0.39},
        { "name": "raptorPenalties:transfer_other", "initial": 0.39},
    ]

    # Extend with index information for CMA-ES evaluation
    variables_map = { v["name"]: v for v in variables }

    active_index = 0

    # First find active variables
    for variable in variables:
        if "fixed" in variable or "copy" in variable: 
            continue

        variables_map[variable["name"]] = variable
        
        variable["index"] = active_index
        variable["optimized"] = True
        active_index += 1

    # Then treat fixed variables and those copying from others
    for variable in variables:
        if "fixed" in variable:
            variable["index"] = None
        
        if "copy" in variable:
            assert not "initial" in variable
            variable["initial"] = variables_map[variable["copy"]]["initial"]
            variable["index"] = variables_map[variable["copy"]]["index"]

    return variables


# Prepare function to convert CMA-ES' candidate to utilities
def prepare_utilities(values, variables):
    utilities = {}
    
    for variable in variables:
        if variable["index"] is not None:
            utilities[variable["name"]] = values[variable["index"]]
        else:
            utilities[variable["name"]] = variable["initial"]
    
    return utilities


# Prepare bounds and initial values
def prepare_bounds_and_initial_values(variables):
    initial = []
    bounds = [[], []]

    for variable in variables:
        if "optimized" in variable:
            initial.append(variable["initial"])
            if variable["name"] == "tram_u_h" or variable["name"] == "bus_u_h":
                bounds[0].append(-1.72)
                bounds[1].append(-1.0)
            elif not "raptorPenalties" in variable["name"]:
                bounds[0].append(-np.inf)
                bounds[1].append(-1.0)
            else:
                bounds[0].append(0.1)
                bounds[1].append(np.inf)

    return initial, bounds


def configure(context):
    context.stage("calibration.pt_routing.prepare_input_data")
    context.stage("calibration.pt_routing.generate_config")
    context.stage("calibration.pt_routing.eqasim")

    context.config("random_seed")


def execute(context):
    random_seed = context.config("random_seed")
    port_number = 8044
    canton      = None

    reference_data = context.stage("calibration.pt_routing.prepare_input_data")

    parameters               = define_parameters(random_seed, port_number, canton)
    parameters, df_reference = calibration_utils.read_reference(reference_data, parameters)
    requests                 = calibration_utils.create_requests(df_reference)
    variables                = initialize_variables()
    initial, bounds          = prepare_bounds_and_initial_values(variables)

    output_path = f"{context.path()}/calibration.p"

    objective = parameters["objective"]
    if objective == "observation_based":
        calculate_objective = calibration_utils.calculate_objective_observation_based
    elif objective == "distribution_based":
        calculate_objective = calibration_utils.calculate_objective_distribution_based
    else:
        raise RuntimeError("Unknown objective")
    
    # Optimizer configuration
    # Configure CMA-ES
    seed       = parameters["seed"]
    sigma      = parameters["sigma"]
    iterations = parameters["iterations"]
    popsize    = parameters["popsize"]

    options = cma.CMAOptions()
    options.set("bounds", bounds)
    options.set("seed", seed)
    options.set("popsize", popsize)

    algorithm = cma.CMAEvolutionStrategy(initial, sigma, options)

    pt_modes = parameters["pt_modes"]
    history = []

    if os.path.exists(output_path):
        with open(output_path, "rb") as f:
            history = pickle.load(f)

            algorithm.feed_for_resume(
                [h["candidate"] for h in history[1:]], 
                [h["objective"] for h in history[1:]]
        )

    for _ in range(iterations):
        initial_evaluation = len(history) == 0
        candidates = [initial]

        if not initial_evaluation:
            candidates = algorithm.ask()

        objectives = []

        # --- Start external process ---
        jar_path = context.stage("calibration.pt_routing.eqasim")
        config_path = context.stage("calibration.pt_routing.generate_config")

        # --- It is ready so let's optimize ---
        for candidate in candidates:
                utilities   = prepare_utilities(candidate, variables)

                transit_utilities = {}
                for key, value in utilities.items():
                    if not "raptorPenalties" in key:
                        transit_utilities[key] = value

                penalties = []

                for key, value in utilities.items():
                    if "raptorPenalties" in key:
                        if "transfer_intermodal" in key:
                            for themode1 in pt_modes:
                                for themode2 in pt_modes:
                                    if themode1 != themode2 and "rail" in [themode1, themode2]:
                                        penalties.append(f"--raptorPenalties:transfer_{themode1}_to_{themode2}")
                                        penalties.append(str(value))
                            
                        if "transfer_rail" in key:
                            themode = "rail"
                            penalties.append(f"--raptorPenalties:transfer_{themode}_to_{themode}")
                            penalties.append(str(value))

                        if "transfer_other" in key:
                            for themode1 in pt_modes:
                                for themode2 in pt_modes:
                                    if not ("rail" in [themode1, themode2]):
                                        penalties.append(f"--raptorPenalties:transfer_{themode1}_to_{themode2}")
                                        penalties.append(str(value))

                server_proc = subprocess.Popen(["java", "-cp", jar_path, "org.eqasim.server.RunServer",
                                         "--config-path", config_path,
                                         "--port", str(port_number),
                                         "--threads", "12",
                                         "--eqasim-configurator", "org.eqasim.switzerland.ch.SwitzerlandConfigurator",
                                         "--use-transit", "true",
                                         "--config:transitRouter.directWalkFactor","3.0"
                                         ] + penalties)
                try:
                    calibration_utils.wait_for_server(parameters["routing_endpoint"], requests[:2], transit_utilities) 

                    df_response = calibration_utils.query_endpoint_batched(parameters, requests, transit_utilities)
                    objective   = calculate_objective(parameters, df_reference, df_response)

                    objectives.append(objective)

                    history.append({
                        "candidate": candidate,
                        "utilities": utilities,
                        "objective": objective,
                        "evaluation": df_response,
                        "initial": initial_evaluation
                    })

                finally:
                    server_proc.terminate()
                    try:
                        server_proc.wait(timeout=5)
                    except subprocess.TimeoutExpired:
                        server_proc.kill()

        if not initial_evaluation:
            algorithm.tell(candidates, objectives)
            algorithm.disp()

        # --- Save after a successful CMA-ES iteration ---
        with open(output_path, "wb+") as f:
            pickle.dump(history, f)

    return output_path

