import os
import logging
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.decomposition import PCA
from sklearn.manifold import TSNE

logger = logging.getLogger("synpp")


def configure(context):
	context.config("analysis_path")
	context.config("matching_embedding_plot_method", "tsne")  # pca | tsne
	context.config("matching_embedding_plot_sample_size", 40000)
	context.config("matching_embedding_plot_alpha", 0.6)
	context.config("matching_embedding_plot_marker_size", 7)
	context.config("random_seed")
	context.config("matching_embedding_plot_top_categories", 12)

	context.stage("synthesis.population.matching.matched_v2")
	context.stage("data.microcensus.persons")


def _reduce_to_2d(X, method="pca", random_seed=865836):
	method = str(method).lower().strip()
	if method == "tsne":
		reducer = TSNE(
			n_components=2,
			random_state=int(random_seed),
			init="pca",
			learning_rate="auto",
			perplexity=30,
		)
		return reducer.fit_transform(X)

	reducer = PCA(n_components=2, random_state=int(random_seed))
	return reducer.fit_transform(X)


def _prepare_labels(series, top_n=12):
	s = series.astype(str).fillna("<na>")
	vc = s.value_counts(dropna=False)
	keep = set(vc.head(int(top_n)).index.tolist())
	return s.where(s.isin(keep), "other")


def _compose_cross_label(df, col_a, col_b):
	if col_a not in df.columns or col_b not in df.columns:
		return None
	a = df[col_a].astype(str).fillna("<na>")
	b = df[col_b].astype(str).fillna("<na>")
	return a + " | " + b


def _plot_scatter(df, x_col, y_col, group_col, out_path, alpha=0.6, marker_size=7, top_categories=12):
	if group_col not in df.columns:
		return

	g = _prepare_labels(df[group_col], top_n=top_categories)
	categories = sorted(g.unique().tolist())

	n = len(categories)
	cmap = plt.cm.get_cmap("tab20", max(n, 2))
	color_map = {cat: cmap(i) for i, cat in enumerate(categories)}

	fig, ax = plt.subplots(figsize=(9, 7), dpi=220)
	for cat in categories:
		mask = (g == cat).values
		if not np.any(mask):
			continue
		ax.scatter(
			df.loc[mask, x_col].values,
			df.loc[mask, y_col].values,
			s=float(marker_size),
			alpha=float(alpha),
			c=[color_map[cat]],
			label=f"{cat} (n={int(np.sum(mask))})",
			linewidths=0,
		)

	ax.set_title(f"MZ embeddings 2D colored by {group_col}")
	ax.set_xlabel(x_col)
	ax.set_ylabel(y_col)
	ax.grid(True, alpha=0.2)
	ax.legend(loc="best", fontsize=7, markerscale=1.8, frameon=True)
	fig.tight_layout()
	fig.savefig(out_path)
	plt.close(fig)


def execute(context):
	# Ensure embeddings are generated by matched_v2.
	context.stage("synthesis.population.matching.matched_v2")

	analysis_path = context.config("analysis_path")
	out_dir = os.path.join(analysis_path, "matching_embedding")
	os.makedirs(out_dir, exist_ok=True)

	method = context.config("matching_embedding_plot_method")
	sample_size = int(context.config("matching_embedding_plot_sample_size"))
	alpha = float(context.config("matching_embedding_plot_alpha"))
	marker_size = float(context.config("matching_embedding_plot_marker_size"))
	random_seed = int(context.config("random_seed"))
	top_categories = int(context.config("matching_embedding_plot_top_categories"))

	emb_stage_path = context.path("synthesis.population.matching.matched_v2")
	emb_file = os.path.join(emb_stage_path, "mz_embeddings", "mz_embeddings.csv")

	if not os.path.exists(emb_file):
		raise RuntimeError(f"Embedding file not found: {emb_file}")

	df_emb = pd.read_csv(emb_file)
	if "person_id" not in df_emb.columns:
		raise RuntimeError("Embedding file must contain 'person_id'.")

	emb_cols = [c for c in df_emb.columns if c.startswith("emb_")]
	if len(emb_cols) == 0:
		raise RuntimeError("Embedding file has no embedding columns (expected emb_*).")

	if sample_size > 0 and len(df_emb) > sample_size:
		df_emb = df_emb.sample(n=sample_size, random_state=random_seed).reset_index(drop=True)

	X = df_emb[emb_cols].astype(float).values
	X2 = _reduce_to_2d(X, method=method, random_seed=random_seed)

	df_2d = df_emb[["person_id"]].copy()
	df_2d["x2d"] = X2[:, 0]
	df_2d["y2d"] = X2[:, 1]

	df_mz = context.stage("data.microcensus.persons").copy()
	meta_cols = [
		"person_id", "sex", "canton_id", "municipality_type", "sp_region",
		"employed", "employment_status", "car_availability", "income_class",
		"work_location_type", "marital_status", "number_of_bikes_class", "ovgk",
	]
	meta_cols = [c for c in meta_cols if c in df_mz.columns]
	df_plot = df_2d.merge(df_mz[meta_cols], on="person_id", how="left")

	# Add cross-effect labels for richer cluster interpretation.
	cross_definitions = [
		("employed", "car_availability", "employed_x_car_availability"),
		("employment_status", "car_availability", "employment_status_x_car_availability"),
		("employed", "ovgk", "employed_x_ovgk"),
	]
	for col_a, col_b, out_col in cross_definitions:
		cross = _compose_cross_label(df_plot, col_a, col_b)
		if cross is not None:
			df_plot[out_col] = cross

	groupings = [
		"sex",
		"canton_id",
		"municipality_type",
		"sp_region",
		"employed",
		"employment_status",
		"work_location_type",
		"car_availability",
		"income_class",
		"ovgk",
		"employed_x_car_availability",
		"employment_status_x_car_availability",
		"employed_x_ovgk",
	]

	generated = []
	for g in groupings:
		if g not in df_plot.columns:
			continue
		out_path = os.path.join(out_dir, f"mz_embeddings_{g}.png")
		_plot_scatter(
			df_plot,
			"x2d",
			"y2d",
			g,
			out_path,
			alpha=alpha,
			marker_size=marker_size,
			top_categories=top_categories,
		)
		generated.append(out_path)

	csv_path = os.path.join(out_dir, "mz_embeddings_2d.csv")
	df_plot.to_csv(csv_path, index=False)

	logger.info("Matching embedding analysis done. Generated %d plots in: %s", len(generated), out_dir)
	return {
		"path": out_dir,
		"embedding_file": emb_file,
		"plots": generated,
		"table": csv_path,
		"n_points": len(df_plot),
		"method": method,
	}
